lfsArch, not arch

diff --git a/baseimages/phase1/nvidia/12.x_20.04/Dockerfile b/baseimages/phase1/nvidia/12.x_20.04/Dockerfile
--- a/baseimages/phase1/nvidia/12.x_20.04/Dockerfile
+++ b/baseimages/phase1/nvidia/12.x_20.04/Dockerfile
@@ -3,6 +3,11 @@ FROM nvidia/cuda:12.2.2-devel-ubuntu20.04
 
 COPY sshd_config /tmp/
 
+# For Git: https://mirrors.edge.kernel.org/pub/software/scm/git/
+ENV GIT_VER=2.45.1 \
+    GIT_LFS_VER=3.5.1 \
+    GRADLE_VER=8.4
+
 # Install the minimum tools
 RUN set -x \
  && export DEBIAN_FRONTEND=noninteractive \
@@ -25,22 +30,33 @@ RUN set -x \
         sudo \
         vim-nox \
         wget \
-# Make sure to install git-lfs
- && curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash \
- && apt-get install -y git-lfs \
+# Create a directory for all the compiled things
+ && mkdir -p /tmp/dl \
 # Install the latest git
  && sudo apt-get install -y \
         libcurl4-gnutls-dev \
         libexpat1-dev \
         libssl-dev \
         zlib1g-dev \
- && export GIT_VER=2.39.3 \
- && cd /tmp && wget -q --no-check-certificate https://mirrors.edge.kernel.org/pub/software/scm/git/git-${GIT_VER}.tar.gz \
+ && wget -q --no-check-certificate https://mirrors.edge.kernel.org/pub/software/scm/git/git-${GIT_VER}.tar.gz \
  && tar -xf git-${GIT_VER}.tar.gz \
  && cd git-${GIT_VER} \
  && make prefix=/usr CFLAGS="-std=gnu99" NO_UNCOMPRESS2=true all \
  && sudo make prefix=/usr CFLAGS="-std=gnu99" NO_UNCOMPRESS2=true install \
- && cd /tmp ; sudo rm -rf v${GIT_VER}.tar.gz git-${GIT_VER}* \
+# Make sure to install git-lfs the direct way. no mucking around with apt
+ && cd /tmp/dl \
+ && arch="$(uname -m)"; \
+       case "$arch" in \
+              x86_64)  lfsArch='amd64' ;; \
+              aarch64) lfsArch='arm64' ;; \
+              ppc64le) lfsArch='ppc64le' ;; \
+              s390x) lfsArch='s390x' ;; \
+              *) echo >&2 "error: unsupported architecture ($arch)"; exit 1 ;;\
+       esac \
+ && wget -q https://github.com/git-lfs/git-lfs/releases/download/v${GIT_LFS_VER}/git-lfs-linux-$lfsArch-v${GIT_LFS_VER}.tar.gz \
+ && tar -xf git-lfs-linux-$arch-v${GIT_LFS_VER}.tar.gz \
+ && cd git-lfs-${GIT_LFS_VER} \
+ && ./install.sh \
 # Store the build tools script into a well known directory
  && mkdir -p /etc/crave \
  && wget -q -O /etc/crave/create_build_tools_json.sh https://github.com/accupara/docker-images/blob/master/baseimages/shared/create_build_tools_json.sh?raw=true \
@@ -55,6 +71,7 @@ RUN set -x \
  && mv /tmp/sshd_config /etc/ssh/sshd_config \
 # Clean up image
  && echo ". /etc/bash_completion" >> /root/.bashrc \
+ && cd /tmp && sudo find dl -delete \
  && apt-get clean \
  && rm -f /var/lib/apt/lists/*_dists_*
 
