golang 1.22 onwards gets the git-lfs fixes too

diff --git a/baseimages/phase1/golang/11-bullseye/1.22/Dockerfile b/baseimages/phase1/golang/11-bullseye/1.22/Dockerfile
--- a/baseimages/phase1/golang/11-bullseye/1.22/Dockerfile
+++ b/baseimages/phase1/golang/11-bullseye/1.22/Dockerfile
@@ -3,7 +3,10 @@ FROM golang:1.22-bullseye
 LABEL org.opencontainers.image.author.name="Crave.io Inc." \
       org.opencontainers.image.author.email="contact@crave.io"
 
-ENV lsb_release_env="bullseye"
+ENV GIT_VER=2.45.1 \
+    GIT_LFS_VER=3.5.1 \
+    lsb_release_env="bullseye"
+
 # Install the minimum tools
 RUN export DEBIAN_FRONTEND=noninteractive \
  && set -x \
@@ -24,22 +27,39 @@ RUN export DEBIAN_FRONTEND=noninteractive \
         subversion \
         sudo \
         vim-nox \
+# Create a directory for all the compiled things
+ && mkdir -p /tmp/dl \
 # Install the latest git
  && eatmydata apt-get install -y \
         libcurl4-gnutls-dev \
         libexpat1-dev \
         libssl-dev \
         zlib1g-dev \
- && export GIT_VER=2.39.3 \
- && cd /tmp && wget -q --no-check-certificate https://mirrors.edge.kernel.org/pub/software/scm/git/git-${GIT_VER}.tar.gz \
- && eatmydata tar -xf git-${GIT_VER}.tar.gz \
+ && cd /tmp/dl \
+ && wget -q --no-check-certificate https://mirrors.edge.kernel.org/pub/software/scm/git/git-${GIT_VER}.tar.gz \
+ && tar -xf git-${GIT_VER}.tar.gz \
  && cd git-${GIT_VER} \
- && eatmydata make prefix=/usr CFLAGS="-std=gnu99" NO_UNCOMPRESS2=true all \
- && eatmydata make prefix=/usr CFLAGS="-std=gnu99" NO_UNCOMPRESS2=true install \
- && cd /tmp ; eatmydata rm -rf v${GIT_VER}.tar.gz git-${GIT_VER}* \
-# Cleanup the apt cache
+ && make prefix=/usr CFLAGS="-std=gnu99" NO_UNCOMPRESS2=true all \
+ && make prefix=/usr CFLAGS="-std=gnu99" NO_UNCOMPRESS2=true install \
+# Make sure to install git-lfs the direct way. no mucking around with apt
+ && cd /tmp/dl \
+ && arch="$(uname -m)"; \
+       case "$arch" in \
+              x86_64)  lfsArch='amd64' ;; \
+              aarch64) lfsArch='arm64' ;; \
+              ppc64le) lfsArch='ppc64le' ;; \
+              s390x) lfsArch='s390x' ;; \
+              *) echo >&2 "error: unsupported architecture ($arch)"; exit 1 ;;\
+       esac \
+ && wget -q https://github.com/git-lfs/git-lfs/releases/download/v${GIT_LFS_VER}/git-lfs-linux-$arch-v${GIT_LFS_VER}.tar.gz \
+ && tar -xf git-lfs-linux-$arch-v${GIT_LFS_VER}.tar.gz \
+ && cd git-lfs-${GIT_LFS_VER} \
+ && ./install.sh \
+# Cleanup the image
+ && cd /tmp \
+ && find /tmp/dl -delete \
  && eatmydata apt-get clean \
- && eatmydata rm -f /var/lib/apt/lists/*_dists_* \
+ && rm -f /var/lib/apt/lists/*_dists_* \
 # bash completion, non-root user and sshd config
  && echo ". /etc/bash_completion" >> /root/.bashrc \
  && useradd -ms /bin/bash admin \
