git and git-lfs for 24.04 and centos 7

diff --git a/baseimages/phase1/ubuntu/24.04/Dockerfile b/baseimages/phase1/ubuntu/24.04/Dockerfile
--- a/baseimages/phase1/ubuntu/24.04/Dockerfile
+++ b/baseimages/phase1/ubuntu/24.04/Dockerfile
@@ -26,6 +26,14 @@ LABEL org.opencontainers.image.author.name="Crave.io Inc." \
 
 COPY sshd_config /tmp/
 
+# https://mirrors.edge.kernel.org/pub/software/scm/git/
+# https://gradle.org/releases/
+# https://github.com/ninja-build/ninja/releases
+ENV GIT_VER=2.45.1 \
+    GIT_LFS_VER=3.5.1 \
+    GRADLE_VER=8.7 \
+    NINJA_VER=v1.12.1
+
 # Install the minimum tools
 RUN set -x \
  && export DEBIAN_FRONTEND=noninteractive \
@@ -41,7 +49,6 @@ RUN set -x \
       dh-make \
       eatmydata \
       emacs \
-      git-lfs \
       guile-3.0 \
       jq \
       libpopt0 \
@@ -63,27 +70,41 @@ RUN set -x \
       xutils-dev \
 # Newest versions of openssh-server don't seem to create all the host keys
  && sudo sudo /usr/bin/ssh-keygen -A \
+# Create a directory for all the compiled things
+ && mkdir -p /tmp/dl \
 # Compile and install the latest git
- && eatmydata -- apt-get install -y \
+ && eatmydata apt-get install -y \
        libcurl4-gnutls-dev \
        libexpat1-dev \
        libssl-dev \
        zlib1g-dev \
- && export GIT_VER=2.42.1 \
- && cd /tmp && wget -q --no-check-certificate https://mirrors.edge.kernel.org/pub/software/scm/git/git-${GIT_VER}.tar.gz \
- && eatmydata -- tar -xf git-${GIT_VER}.tar.gz \
+ && cd /tmp/dl \
+ && wget -q --no-check-certificate https://mirrors.edge.kernel.org/pub/software/scm/git/git-${GIT_VER}.tar.gz \
+ && tar -xf git-${GIT_VER}.tar.gz \
  && cd git-${GIT_VER} \
- && eatmydata -- make prefix=/usr CFLAGS="-std=gnu99" NO_UNCOMPRESS2=true all -j `nproc` \
- && eatmydata -- make prefix=/usr CFLAGS="-std=gnu99" NO_UNCOMPRESS2=true install \
- && cd /tmp ; eatmydata -- rm -rf v${GIT_VER}.tar.gz git-${GIT_VER}* \
+ && make prefix=/usr CFLAGS="-std=gnu99" NO_UNCOMPRESS2=true all -j `nproc` \
+ && make prefix=/usr CFLAGS="-std=gnu99" NO_UNCOMPRESS2=true install \
+# Make sure to install git-lfs the direct way. no mucking around with apt
+ && cd /tmp/dl \
+ && arch="$(uname -m)"; \
+       case "$arch" in \
+              x86_64)  lfsArch='amd64' ;; \
+              aarch64) lfsArch='arm64' ;; \
+              ppc64le) lfsArch='ppc64le' ;; \
+              s390x) lfsArch='s390x' ;; \
+              *) echo >&2 "error: unsupported architecture ($arch)"; exit 1 ;;\
+       esac \
+ && wget -q https://github.com/git-lfs/git-lfs/releases/download/v${GIT_LFS_VER}/git-lfs-linux-$lfsArch-v${GIT_LFS_VER}.tar.gz \
+ && tar -xf git-lfs-linux-$lfsArch-v${GIT_LFS_VER}.tar.gz \
+ && cd git-lfs-${GIT_LFS_VER} \
+ && ./install.sh \
 # Install the latest version of gradle
- && cd /tmp \
+ && cd /tmp/dl \
  && export GRADLE_VER=8.4 \
  && wget -q https://services.gradle.org/distributions/gradle-${GRADLE_VER}-bin.zip \
  && eatmydata -- unzip gradle-${GRADLE_VER}-bin.zip \
  && mv gradle-${GRADLE_VER} /usr/lib/ \
  && ln -sf /usr/lib/gradle-${GRADLE_VER}/bin/gradle /usr/bin/gradle \
- && rm gradle-${GRADLE_VER}-bin.zip \
 # Install the latest version of repo, as described in https://gerrit.googlesource.com/git-repo
  && curl https://storage.googleapis.com/git-repo-downloads/repo >/tmp/repo \
  && sudo mv /tmp/repo /usr/bin/repo \
@@ -105,6 +126,8 @@ RUN set -x \
  && mv /tmp/sshd_config /etc/ssh/sshd_config \
 # Clean up image
  && echo ". /etc/bash_completion" >>/root/.bashrc \
+ && cd /tmp \
+ && find /tmp/dl -delete \
  && apt-get clean \
  && rm -f /var/lib/apt/lists/*_dists_*
 
